-- Initial schema for the Freight Recovery web API.
-- Generated by `prisma migrate diff` and hand-extended (security section at the end):
-- CHECK constraints, row-level security (fail closed), least-privilege grants for the runtime role,
-- and append-only / immutability triggers. Run as the schema owner (freight_owner).

-- Role guard: the runtime role must exist before grants are applied.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'freight_app') THEN
    RAISE EXCEPTION 'Role freight_app does not exist. Apply api/db/init/00-roles.sql as a superuser before running migrations.';
  END IF;
END
$$;

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('OWNER', 'ADMIN', 'MANAGER', 'REVIEWER', 'ANALYST', 'VIEWER');

-- CreateEnum
CREATE TYPE "PlatformRole" AS ENUM ('PLATFORM_DEV', 'SUPER_ADMIN');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'DISABLED');

-- CreateEnum
CREATE TYPE "TenantStatus" AS ENUM ('ACTIVE', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "Perspective" AS ENUM ('SHIPPER', 'CARRIER');

-- CreateEnum
CREATE TYPE "ClaimStatus" AS ENUM ('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'SEND_READY');

-- CreateEnum
CREATE TYPE "PacketStatus" AS ENUM ('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'SEND_READY', 'SUPERSEDED');

-- CreateEnum
CREATE TYPE "ApprovalAction" AS ENUM ('EDIT', 'APPROVE', 'REJECT', 'SEND_READY');

-- CreateEnum
CREATE TYPE "DocType" AS ENUM ('INVOICE', 'RATE_CONFIRMATION', 'BILL_OF_LADING', 'OTHER');

-- CreateEnum
CREATE TYPE "TimelineKind" AS ENUM ('APPOINTMENT', 'ARRIVAL', 'DEPARTURE', 'INVOICE', 'RATE_CONFIRMATION', 'NOTE');

-- CreateEnum
CREATE TYPE "Direction" AS ENUM ('OVERCHARGE', 'UNDERBILLED');

-- CreateEnum
CREATE TYPE "VerifierStatus" AS ENUM ('NOT_RUN', 'PASSED', 'FAILED', 'NEEDS_REVIEW');

-- CreateEnum
CREATE TYPE "MailKind" AS ENUM ('PASSWORD_RESET', 'INVITE');

-- CreateEnum
CREATE TYPE "LoginOutcome" AS ENUM ('SUCCESS', 'BAD_PASSWORD', 'BAD_MFA', 'LOCKED', 'UNKNOWN_USER', 'DISABLED');

-- CreateTable
CREATE TABLE "tenants" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "status" "TenantStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "platform_role" "PlatformRole",
    "password_changed_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_login_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "id" UUID NOT NULL,
    "family_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "parent_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "family_expires_at" TIMESTAMPTZ(3) NOT NULL,
    "used_at" TIMESTAMPTZ(3),
    "revoked_at" TIMESTAMPTZ(3),
    "revoked_reason" TEXT,
    "ip" TEXT,
    "user_agent_hash" TEXT,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mfa_secrets" (
    "user_id" UUID NOT NULL,
    "ciphertext" BYTEA NOT NULL,
    "nonce" BYTEA NOT NULL,
    "key_id" TEXT NOT NULL,
    "verified_at" TIMESTAMPTZ(3),
    "last_used_step" BIGINT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mfa_secrets_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "mfa_recovery_codes" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "code_hash" TEXT NOT NULL,
    "used_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mfa_recovery_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "login_attempts" (
    "id" UUID NOT NULL,
    "email_hash" TEXT NOT NULL,
    "ip" TEXT,
    "outcome" "LoginOutcome" NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "login_attempts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "login_lockouts" (
    "email_hash" TEXT NOT NULL,
    "failures" INTEGER NOT NULL DEFAULT 0,
    "locked_until" TIMESTAMPTZ(3),
    "last_failure_at" TIMESTAMPTZ(3),

    CONSTRAINT "login_lockouts_pkey" PRIMARY KEY ("email_hash")
);

-- CreateTable
CREATE TABLE "password_resets" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "used_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "password_resets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mail_outbox" (
    "id" UUID NOT NULL,
    "to_email" TEXT NOT NULL,
    "kind" "MailKind" NOT NULL,
    "token" TEXT NOT NULL,
    "tenant_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "mail_outbox_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "memberships" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role" "Role" NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "memberships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "invites" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "role" "Role" NOT NULL,
    "token_hash" TEXT NOT NULL,
    "invited_by_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "accepted_at" TIMESTAMPTZ(3),
    "revoked_at" TIMESTAMPTZ(3),

    CONSTRAINT "invites_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "claims" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "claim_number" TEXT NOT NULL,
    "load_number" TEXT,
    "invoice_number" TEXT,
    "invoice_date" TIMESTAMPTZ(3),
    "carrier_name" TEXT NOT NULL,
    "shipper_name" TEXT NOT NULL,
    "perspective" "Perspective" NOT NULL,
    "status" "ClaimStatus" NOT NULL DEFAULT 'PENDING_REVIEW',
    "amount_claimed_cents" INTEGER NOT NULL,
    "recoverable_cents" INTEGER NOT NULL,
    "pending_review_cents" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "assignee_id" UUID,
    "version" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "claims_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "evidence_packets" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "claim_id" UUID NOT NULL,
    "revision" INTEGER NOT NULL,
    "status" "PacketStatus" NOT NULL DEFAULT 'PENDING_REVIEW',
    "perspective" "Perspective" NOT NULL,
    "load_number" TEXT,
    "generated_at" TIMESTAMPTZ(3) NOT NULL,
    "disclaimer" TEXT NOT NULL,
    "demand_letter" TEXT NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "recoverable_cents" INTEGER NOT NULL,
    "pending_review_cents" INTEGER NOT NULL,
    "verifier_status" "VerifierStatus" NOT NULL DEFAULT 'NOT_RUN',
    "verifier_checked_at" TIMESTAMPTZ(3),
    "verifier_note" TEXT,
    "content_hash" TEXT NOT NULL,
    "created_by_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "evidence_packets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "packet_sources" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "packet_id" UUID NOT NULL,
    "filename" TEXT NOT NULL,
    "doc_type" "DocType" NOT NULL,
    "sha256" TEXT NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "ordinal" INTEGER NOT NULL,

    CONSTRAINT "packet_sources_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "packet_timeline_events" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "packet_id" UUID NOT NULL,
    "occurred_at" TIMESTAMPTZ(3) NOT NULL,
    "kind" "TimelineKind" NOT NULL,
    "label" TEXT NOT NULL,
    "source_id" UUID,
    "ordinal" INTEGER NOT NULL,

    CONSTRAINT "packet_timeline_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "packet_findings" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "packet_id" UUID NOT NULL,
    "ordinal" INTEGER NOT NULL,
    "rule_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "direction" "Direction" NOT NULL,
    "amount_cents" INTEGER NOT NULL,
    "explanation" TEXT NOT NULL,
    "calculation" JSONB NOT NULL,
    "confidence" DECIMAL(4,3) NOT NULL,
    "needs_human_review" BOOLEAN NOT NULL,
    "citations" JSONB NOT NULL,
    "clause_source_id" UUID,
    "clause_label" TEXT,
    "clause_excerpt" TEXT,
    "clause_locator" TEXT,

    CONSTRAINT "packet_findings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "approvals" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "claim_id" UUID NOT NULL,
    "packet_id" UUID NOT NULL,
    "packet_revision" INTEGER NOT NULL,
    "action" "ApprovalAction" NOT NULL,
    "reason" TEXT NOT NULL,
    "from_status" TEXT NOT NULL,
    "to_status" TEXT NOT NULL,
    "content_hash" TEXT NOT NULL,
    "actor_id" UUID NOT NULL,
    "actor_role" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "approvals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_events" (
    "id" UUID NOT NULL,
    "chain_key" TEXT NOT NULL,
    "tenant_id" UUID,
    "seq" BIGINT NOT NULL,
    "actor_id" UUID,
    "actor_role" TEXT,
    "action" TEXT NOT NULL,
    "target_type" TEXT,
    "target_id" TEXT,
    "metadata" JSONB NOT NULL,
    "ip" TEXT,
    "request_id" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL,
    "prev_hash" TEXT NOT NULL,
    "hash" TEXT NOT NULL,

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "tenants_slug_key" ON "tenants"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_token_hash_key" ON "refresh_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "refresh_tokens_family_id_idx" ON "refresh_tokens"("family_id");

-- CreateIndex
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens"("user_id");

-- CreateIndex
CREATE INDEX "mfa_recovery_codes_user_id_idx" ON "mfa_recovery_codes"("user_id");

-- CreateIndex
CREATE INDEX "login_attempts_email_hash_created_at_idx" ON "login_attempts"("email_hash", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "password_resets_token_hash_key" ON "password_resets"("token_hash");

-- CreateIndex
CREATE INDEX "password_resets_user_id_idx" ON "password_resets"("user_id");

-- CreateIndex
CREATE INDEX "mail_outbox_to_email_created_at_idx" ON "mail_outbox"("to_email", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "memberships_user_id_key" ON "memberships"("user_id");

-- CreateIndex
CREATE INDEX "memberships_tenant_id_idx" ON "memberships"("tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "invites_token_hash_key" ON "invites"("token_hash");

-- CreateIndex
CREATE INDEX "invites_tenant_id_idx" ON "invites"("tenant_id");

-- CreateIndex
CREATE INDEX "claims_tenant_id_status_idx" ON "claims"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "claims_tenant_id_updated_at_idx" ON "claims"("tenant_id", "updated_at");

-- CreateIndex
CREATE INDEX "claims_tenant_id_created_at_idx" ON "claims"("tenant_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "claims_tenant_id_claim_number_key" ON "claims"("tenant_id", "claim_number");

-- CreateIndex
CREATE UNIQUE INDEX "claims_id_tenant_id_key" ON "claims"("id", "tenant_id");

-- CreateIndex
CREATE INDEX "evidence_packets_tenant_id_status_idx" ON "evidence_packets"("tenant_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "evidence_packets_claim_id_revision_key" ON "evidence_packets"("claim_id", "revision");

-- CreateIndex
CREATE UNIQUE INDEX "evidence_packets_id_tenant_id_key" ON "evidence_packets"("id", "tenant_id");

-- CreateIndex
CREATE UNIQUE INDEX "packet_sources_packet_id_ordinal_key" ON "packet_sources"("packet_id", "ordinal");

-- CreateIndex
CREATE UNIQUE INDEX "packet_timeline_events_packet_id_ordinal_key" ON "packet_timeline_events"("packet_id", "ordinal");

-- CreateIndex
CREATE UNIQUE INDEX "packet_findings_packet_id_ordinal_key" ON "packet_findings"("packet_id", "ordinal");

-- CreateIndex
CREATE INDEX "approvals_tenant_id_claim_id_created_at_idx" ON "approvals"("tenant_id", "claim_id", "created_at");

-- CreateIndex
CREATE INDEX "audit_events_tenant_id_seq_idx" ON "audit_events"("tenant_id", "seq");

-- CreateIndex
CREATE UNIQUE INDEX "audit_events_chain_key_seq_key" ON "audit_events"("chain_key", "seq");

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mfa_secrets" ADD CONSTRAINT "mfa_secrets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mfa_recovery_codes" ADD CONSTRAINT "mfa_recovery_codes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "password_resets" ADD CONSTRAINT "password_resets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invites" ADD CONSTRAINT "invites_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invites" ADD CONSTRAINT "invites_invited_by_id_fkey" FOREIGN KEY ("invited_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "claims" ADD CONSTRAINT "claims_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "claims" ADD CONSTRAINT "claims_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_packets" ADD CONSTRAINT "evidence_packets_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_packets" ADD CONSTRAINT "evidence_packets_claim_id_tenant_id_fkey" FOREIGN KEY ("claim_id", "tenant_id") REFERENCES "claims"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "evidence_packets" ADD CONSTRAINT "evidence_packets_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packet_sources" ADD CONSTRAINT "packet_sources_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packet_sources" ADD CONSTRAINT "packet_sources_packet_id_tenant_id_fkey" FOREIGN KEY ("packet_id", "tenant_id") REFERENCES "evidence_packets"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packet_timeline_events" ADD CONSTRAINT "packet_timeline_events_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packet_timeline_events" ADD CONSTRAINT "packet_timeline_events_packet_id_tenant_id_fkey" FOREIGN KEY ("packet_id", "tenant_id") REFERENCES "evidence_packets"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packet_findings" ADD CONSTRAINT "packet_findings_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "packet_findings" ADD CONSTRAINT "packet_findings_packet_id_tenant_id_fkey" FOREIGN KEY ("packet_id", "tenant_id") REFERENCES "evidence_packets"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_claim_id_tenant_id_fkey" FOREIGN KEY ("claim_id", "tenant_id") REFERENCES "claims"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_packet_id_tenant_id_fkey" FOREIGN KEY ("packet_id", "tenant_id") REFERENCES "evidence_packets"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- =============================================================================================
-- SECURITY SECTION (hand-written)
-- =============================================================================================

-- ---------------------------------------------------------------------------------------------
-- CHECK constraints and partial unique indexes
-- ---------------------------------------------------------------------------------------------
ALTER TABLE "users" ADD CONSTRAINT "users_email_lowercase" CHECK (email = lower(email) AND char_length(email) <= 254);
ALTER TABLE "invites" ADD CONSTRAINT "invites_email_lowercase" CHECK (email = lower(email) AND char_length(email) <= 254);
ALTER TABLE "invites" ADD CONSTRAINT "invites_role_not_owner" CHECK (role <> 'OWNER');
ALTER TABLE "login_lockouts" ADD CONSTRAINT "login_lockouts_failures_nonneg" CHECK (failures >= 0);
ALTER TABLE "claims" ADD CONSTRAINT "claims_amounts_nonneg"
  CHECK (amount_claimed_cents >= 0 AND recoverable_cents >= 0 AND pending_review_cents >= 0);
ALTER TABLE "claims" ADD CONSTRAINT "claims_currency_usd" CHECK (currency = 'USD');
ALTER TABLE "claims" ADD CONSTRAINT "claims_version_nonneg" CHECK (version >= 0);
ALTER TABLE "evidence_packets" ADD CONSTRAINT "evidence_packets_amounts_nonneg"
  CHECK (recoverable_cents >= 0 AND pending_review_cents >= 0);
ALTER TABLE "evidence_packets" ADD CONSTRAINT "evidence_packets_revision_positive" CHECK (revision >= 1);
ALTER TABLE "evidence_packets" ADD CONSTRAINT "evidence_packets_currency_usd" CHECK (currency = 'USD');
ALTER TABLE "evidence_packets" ADD CONSTRAINT "evidence_packets_content_hash_hex" CHECK (content_hash ~ '^[0-9a-f]{64}$');
ALTER TABLE "packet_sources" ADD CONSTRAINT "packet_sources_size_nonneg" CHECK (size_bytes >= 0);
ALTER TABLE "packet_findings" ADD CONSTRAINT "packet_findings_amount_nonneg" CHECK (amount_cents >= 0);
ALTER TABLE "packet_findings" ADD CONSTRAINT "packet_findings_confidence_range" CHECK (confidence BETWEEN 0 AND 1);
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_reason_length" CHECK (char_length(reason) BETWEEN 10 AND 2000);
ALTER TABLE "approvals" ADD CONSTRAINT "approvals_revision_positive" CHECK (packet_revision >= 1);
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_seq_positive" CHECK (seq >= 1);
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_hashes_hex"
  CHECK (hash ~ '^[0-9a-f]{64}$' AND prev_hash ~ '^[0-9a-f]{64}$');
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_chain_key_matches_tenant"
  CHECK ((tenant_id IS NULL AND chain_key = 'platform') OR (tenant_id IS NOT NULL AND chain_key = 't:' || tenant_id::text));

-- At most one non-superseded packet revision per claim.
CREATE UNIQUE INDEX "evidence_packets_one_live_revision" ON "evidence_packets"("claim_id") WHERE status <> 'SUPERSEDED';
-- At most one pending invite per (tenant, email).
CREATE UNIQUE INDEX "invites_one_pending_per_email" ON "invites"("tenant_id", "email")
  WHERE accepted_at IS NULL AND revoked_at IS NULL;

-- ---------------------------------------------------------------------------------------------
-- Tenant context helpers. With no setting, both return "nothing" so RLS fails closed.
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION fr_current_tenant() RETURNS uuid
  LANGUAGE sql STABLE
  AS $$ SELECT nullif(current_setting('app.tenant_id', true), '')::uuid $$;

CREATE FUNCTION fr_system_mode() RETURNS boolean
  LANGUAGE sql STABLE
  AS $$ SELECT coalesce(current_setting('app.system', true), '') = 'on' $$;

-- ---------------------------------------------------------------------------------------------
-- Row-level security on every tenant-scoped table. FORCE applies it to the table owner as well;
-- only roles with BYPASSRLS (freight_owner: migrations, seed, test fixtures) skip it.
-- ---------------------------------------------------------------------------------------------
ALTER TABLE "claims" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "claims" FORCE ROW LEVEL SECURITY;
CREATE POLICY "claims_tenant_isolation" ON "claims" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

ALTER TABLE "evidence_packets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "evidence_packets" FORCE ROW LEVEL SECURITY;
CREATE POLICY "evidence_packets_tenant_isolation" ON "evidence_packets" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

ALTER TABLE "packet_sources" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "packet_sources" FORCE ROW LEVEL SECURITY;
CREATE POLICY "packet_sources_tenant_isolation" ON "packet_sources" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

ALTER TABLE "packet_timeline_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "packet_timeline_events" FORCE ROW LEVEL SECURITY;
CREATE POLICY "packet_timeline_events_tenant_isolation" ON "packet_timeline_events" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

ALTER TABLE "packet_findings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "packet_findings" FORCE ROW LEVEL SECURITY;
CREATE POLICY "packet_findings_tenant_isolation" ON "packet_findings" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

ALTER TABLE "approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "approvals" FORCE ROW LEVEL SECURITY;
CREATE POLICY "approvals_tenant_isolation" ON "approvals" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

-- The auth bootstrap reads memberships/invites before a tenant is known (system mode only).
ALTER TABLE "memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "memberships" FORCE ROW LEVEL SECURITY;
CREATE POLICY "memberships_tenant_isolation" ON "memberships" FOR ALL
  USING (tenant_id = fr_current_tenant() OR fr_system_mode())
  WITH CHECK (tenant_id = fr_current_tenant() OR fr_system_mode());

ALTER TABLE "invites" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invites" FORCE ROW LEVEL SECURITY;
CREATE POLICY "invites_tenant_isolation" ON "invites" FOR ALL
  USING (tenant_id = fr_current_tenant() OR fr_system_mode())
  WITH CHECK (tenant_id = fr_current_tenant() OR fr_system_mode());

-- The platform chain (tenant_id NULL) is reachable only in system mode.
ALTER TABLE "audit_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_events" FORCE ROW LEVEL SECURITY;
CREATE POLICY "audit_events_tenant_isolation" ON "audit_events" FOR ALL
  USING (tenant_id = fr_current_tenant() OR (tenant_id IS NULL AND fr_system_mode()))
  WITH CHECK (tenant_id = fr_current_tenant() OR (tenant_id IS NULL AND fr_system_mode()));

-- ---------------------------------------------------------------------------------------------
-- Append-only and immutability triggers. They also block the owner; `db:seed -- --reset` sets
-- session_replication_role=replica inside its own session only (granted in 00-roles.sql).
-- ---------------------------------------------------------------------------------------------
CREATE FUNCTION fr_append_only() RETURNS trigger
  LANGUAGE plpgsql
  AS $$
BEGIN
  RAISE EXCEPTION 'append_only' USING ERRCODE = 'P0001', DETAIL = TG_TABLE_NAME;
END
$$;

CREATE TRIGGER "audit_events_append_only" BEFORE UPDATE OR DELETE ON "audit_events" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "audit_events_no_truncate" BEFORE TRUNCATE ON "audit_events" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "approvals_append_only" BEFORE UPDATE OR DELETE ON "approvals" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "approvals_no_truncate" BEFORE TRUNCATE ON "approvals" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "login_attempts_append_only" BEFORE UPDATE OR DELETE ON "login_attempts" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "login_attempts_no_truncate" BEFORE TRUNCATE ON "login_attempts" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "packet_sources_append_only" BEFORE UPDATE OR DELETE ON "packet_sources" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "packet_sources_no_truncate" BEFORE TRUNCATE ON "packet_sources" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "packet_timeline_events_append_only" BEFORE UPDATE OR DELETE ON "packet_timeline_events" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "packet_timeline_events_no_truncate" BEFORE TRUNCATE ON "packet_timeline_events" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "packet_findings_append_only" BEFORE UPDATE OR DELETE ON "packet_findings" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "packet_findings_no_truncate" BEFORE TRUNCATE ON "packet_findings" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();

-- Evidence packets: only `status` may change, and only along the review state machine.
CREATE FUNCTION fr_packet_update_guard() RETURNS trigger
  LANGUAGE plpgsql
  AS $$
BEGIN
  IF (to_jsonb(NEW) - 'status') IS DISTINCT FROM (to_jsonb(OLD) - 'status') THEN
    RAISE EXCEPTION 'packet_immutable' USING ERRCODE = 'P0001';
  END IF;
  IF NEW.status = OLD.status THEN
    RETURN NEW;
  END IF;
  IF (OLD.status = 'PENDING_REVIEW' AND NEW.status IN ('APPROVED', 'REJECTED', 'SUPERSEDED'))
     OR (OLD.status = 'APPROVED' AND NEW.status IN ('SEND_READY', 'SUPERSEDED'))
     OR (OLD.status = 'REJECTED' AND NEW.status = 'SUPERSEDED') THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'invalid_packet_transition' USING ERRCODE = 'P0001';
END
$$;

CREATE TRIGGER "evidence_packets_update_guard" BEFORE UPDATE ON "evidence_packets" FOR EACH ROW EXECUTE FUNCTION fr_packet_update_guard();
CREATE TRIGGER "evidence_packets_no_delete" BEFORE DELETE ON "evidence_packets" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "evidence_packets_no_truncate" BEFORE TRUNCATE ON "evidence_packets" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();

-- A user is EITHER a platform user (platform_role set, no membership) OR a tenant user
-- (no platform_role, one membership). Checked at commit (deferred) so the user and its membership
-- can be created in one transaction. SECURITY DEFINER (owner has BYPASSRLS) so RLS does not hide rows.
CREATE FUNCTION fr_user_kind_check() RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public, pg_temp
  AS $$
DECLARE
  uid uuid;
  prole text;
  has_membership boolean;
BEGIN
  IF TG_TABLE_NAME = 'users' THEN
    uid := NEW.id;
  ELSE
    uid := NEW.user_id;
  END IF;
  SELECT platform_role::text INTO prole FROM users WHERE id = uid;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  SELECT EXISTS (SELECT 1 FROM memberships WHERE user_id = uid) INTO has_membership;
  IF prole IS NULL AND NOT has_membership THEN
    RAISE EXCEPTION 'user_kind: tenant user without membership' USING ERRCODE = 'P0001';
  END IF;
  IF prole IS NOT NULL AND has_membership THEN
    RAISE EXCEPTION 'user_kind: platform user with membership' USING ERRCODE = 'P0001';
  END IF;
  RETURN NULL;
END
$$;

CREATE CONSTRAINT TRIGGER "users_kind_check" AFTER INSERT OR UPDATE ON "users"
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION fr_user_kind_check();
CREATE CONSTRAINT TRIGGER "memberships_kind_check" AFTER INSERT OR UPDATE ON "memberships"
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION fr_user_kind_check();

-- Platform tenant statistics: counts only (no tenant content); callable only in system mode.
CREATE FUNCTION fr_platform_tenant_stats() RETURNS TABLE (tenant_id uuid, user_count bigint, claim_count bigint)
  LANGUAGE plpgsql
  STABLE
  SECURITY DEFINER
  SET search_path = public, pg_temp
  AS $$
BEGIN
  IF NOT fr_system_mode() THEN
    RAISE EXCEPTION 'system mode required' USING ERRCODE = 'P0001';
  END IF;
  RETURN QUERY
    SELECT t.id,
           (SELECT count(*) FROM memberships m WHERE m.tenant_id = t.id),
           (SELECT count(*) FROM claims c WHERE c.tenant_id = t.id)
    FROM tenants t;
END
$$;

-- ---------------------------------------------------------------------------------------------
-- Least-privilege grants for the runtime role (no TRUNCATE, no DDL, no BYPASSRLS).
-- ---------------------------------------------------------------------------------------------
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON FUNCTION fr_user_kind_check() FROM PUBLIC;
REVOKE ALL ON FUNCTION fr_platform_tenant_stats() FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO freight_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON
  "users", "tenants", "memberships", "invites", "claims", "refresh_tokens", "mfa_secrets",
  "mfa_recovery_codes", "login_lockouts", "password_resets", "mail_outbox"
  TO freight_app;
GRANT SELECT, INSERT ON "evidence_packets" TO freight_app;
GRANT UPDATE ("status") ON "evidence_packets" TO freight_app;
GRANT SELECT, INSERT ON
  "packet_sources", "packet_timeline_events", "packet_findings", "approvals", "audit_events", "login_attempts"
  TO freight_app;
GRANT EXECUTE ON FUNCTION fr_current_tenant() TO freight_app;
GRANT EXECUTE ON FUNCTION fr_system_mode() TO freight_app;
GRANT EXECUTE ON FUNCTION fr_platform_tenant_stats() TO freight_app;
