-- Step 3 (Import + Export): import batches, documents, extracted fields with provenance, review
-- decisions and document -> claim links; ClaimStatus AWAITING_ANALYSIS.
-- Generated by `prisma migrate diff` and hand-extended (security section at the end): CHECK constraints,
-- row-level security (fail closed), least-privilege grants for the runtime role, and append-only /
-- immutability triggers, following the pattern of 20261008000000_init. Run as freight_owner.
--
-- ClaimStatus gains AWAITING_ANALYSIS via ALTER TYPE ... ADD VALUE; nothing in this migration uses the
-- new value (it cannot be used inside the transaction that adds it).

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'freight_app') THEN
    RAISE EXCEPTION 'Role freight_app does not exist. Apply api/db/init/00-roles.sql as a superuser before running migrations.';
  END IF;
END
$$;

-- CreateEnum
CREATE TYPE "ImportSource" AS ENUM ('UPLOAD', 'EMAIL');

-- CreateEnum
CREATE TYPE "DetectedType" AS ENUM ('PDF', 'PNG', 'JPEG', 'CSV', 'TXT');

-- CreateEnum
CREATE TYPE "ImportDocStatus" AS ENUM ('RECEIVED', 'NEEDS_REVIEW', 'ACCEPTED', 'REJECTED', 'FAILED');

-- CreateEnum
CREATE TYPE "DocTypeBasis" AS ENUM ('HEADER', 'KEYS', 'FILENAME', 'MANUAL', 'NONE');

-- CreateEnum
CREATE TYPE "FieldKind" AS ENUM ('STRING', 'DECIMAL', 'DATETIME', 'STRING_LIST');

-- CreateEnum
CREATE TYPE "FieldStatus" AS ENUM ('PROPOSED', 'CONFIRMED', 'CORRECTED', 'REJECTED');

-- CreateEnum
CREATE TYPE "FieldOrigin" AS ENUM ('EXTRACTED', 'MANUAL');

-- CreateEnum
CREATE TYPE "ReviewAction" AS ENUM ('CONFIRM', 'CORRECT', 'REJECT', 'ADD', 'SET_TYPE', 'ACCEPT', 'REJECT_DOC');

-- AlterEnum
ALTER TYPE "ClaimStatus" ADD VALUE 'AWAITING_ANALYSIS';

-- CreateTable
CREATE TABLE "import_batches" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "label" TEXT,
    "source" "ImportSource" NOT NULL DEFAULT 'UPLOAD',
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "import_batches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "import_documents" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "batch_id" UUID NOT NULL,
    "uploaded_by_id" UUID,
    "source" "ImportSource" NOT NULL,
    "source_ref" TEXT,
    "display_name" TEXT NOT NULL,
    "detected_type" "DetectedType" NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "sha256" CHAR(64) NOT NULL,
    "storage_key" TEXT,
    "text_key" TEXT,
    "doc_type" "DocType" NOT NULL,
    "doc_type_basis" "DocTypeBasis" NOT NULL,
    "status" "ImportDocStatus" NOT NULL,
    "reject_reason" TEXT,
    "review_reasons" TEXT[],
    "warnings" TEXT[],
    "page_count" INTEGER,
    "char_count" INTEGER,
    "load_number" TEXT,
    "provider_name" TEXT NOT NULL,
    "provider_version" TEXT NOT NULL,
    "parser_version" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "parsed_at" TIMESTAMPTZ(3),

    CONSTRAINT "import_documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "extracted_fields" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "document_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "group_index" INTEGER,
    "ordinal" INTEGER NOT NULL,
    "kind" "FieldKind" NOT NULL,
    "value" TEXT,
    "raw_value" TEXT NOT NULL,
    "corrected_value" TEXT,
    "confidence" DECIMAL(4,3) NOT NULL,
    "needs_review" BOOLEAN NOT NULL,
    "review_reasons" TEXT[],
    "status" "FieldStatus" NOT NULL DEFAULT 'PROPOSED',
    "origin" "FieldOrigin" NOT NULL,
    "page" INTEGER,
    "line" INTEGER,
    "start_col" INTEGER,
    "end_col" INTEGER,
    "source_row" INTEGER,
    "excerpt" TEXT,
    "resolved_by_id" UUID,
    "resolved_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "extracted_fields_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "import_review_decisions" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "document_id" UUID NOT NULL,
    "field_id" UUID,
    "action" "ReviewAction" NOT NULL,
    "reason" TEXT NOT NULL,
    "before_value_sha256" TEXT,
    "after_value_sha256" TEXT,
    "actor_id" UUID NOT NULL,
    "actor_role" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "import_review_decisions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "claim_documents" (
    "id" UUID NOT NULL,
    "tenant_id" UUID NOT NULL,
    "claim_id" UUID NOT NULL,
    "document_id" UUID NOT NULL,
    "linked_by_id" UUID NOT NULL,
    "linked_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "claim_documents_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "import_batches_tenant_id_created_at_idx" ON "import_batches"("tenant_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "import_batches_id_tenant_id_key" ON "import_batches"("id", "tenant_id");

-- CreateIndex
CREATE INDEX "import_documents_tenant_id_batch_id_idx" ON "import_documents"("tenant_id", "batch_id");

-- CreateIndex
CREATE INDEX "import_documents_tenant_id_status_created_at_idx" ON "import_documents"("tenant_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "import_documents_tenant_id_sha256_idx" ON "import_documents"("tenant_id", "sha256");

-- CreateIndex
CREATE UNIQUE INDEX "import_documents_tenant_id_batch_id_sha256_key" ON "import_documents"("tenant_id", "batch_id", "sha256");

-- CreateIndex
CREATE UNIQUE INDEX "import_documents_id_tenant_id_key" ON "import_documents"("id", "tenant_id");

-- CreateIndex
CREATE INDEX "extracted_fields_tenant_id_document_id_idx" ON "extracted_fields"("tenant_id", "document_id");

-- CreateIndex
CREATE UNIQUE INDEX "extracted_fields_id_tenant_id_key" ON "extracted_fields"("id", "tenant_id");

-- CreateIndex
CREATE INDEX "import_review_decisions_tenant_id_document_id_created_at_idx" ON "import_review_decisions"("tenant_id", "document_id", "created_at");

-- CreateIndex
CREATE INDEX "claim_documents_tenant_id_claim_id_idx" ON "claim_documents"("tenant_id", "claim_id");

-- CreateIndex
CREATE UNIQUE INDEX "claim_documents_tenant_id_document_id_key" ON "claim_documents"("tenant_id", "document_id");

-- AddForeignKey
ALTER TABLE "import_batches" ADD CONSTRAINT "import_batches_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_batches" ADD CONSTRAINT "import_batches_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_batch_id_tenant_id_fkey" FOREIGN KEY ("batch_id", "tenant_id") REFERENCES "import_batches"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_uploaded_by_id_fkey" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_document_id_tenant_id_fkey" FOREIGN KEY ("document_id", "tenant_id") REFERENCES "import_documents"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_resolved_by_id_fkey" FOREIGN KEY ("resolved_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_review_decisions" ADD CONSTRAINT "import_review_decisions_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_review_decisions" ADD CONSTRAINT "import_review_decisions_document_id_tenant_id_fkey" FOREIGN KEY ("document_id", "tenant_id") REFERENCES "import_documents"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_review_decisions" ADD CONSTRAINT "import_review_decisions_field_id_tenant_id_fkey" FOREIGN KEY ("field_id", "tenant_id") REFERENCES "extracted_fields"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_review_decisions" ADD CONSTRAINT "import_review_decisions_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "claim_documents" ADD CONSTRAINT "claim_documents_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "claim_documents" ADD CONSTRAINT "claim_documents_claim_id_tenant_id_fkey" FOREIGN KEY ("claim_id", "tenant_id") REFERENCES "claims"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "claim_documents" ADD CONSTRAINT "claim_documents_document_id_tenant_id_fkey" FOREIGN KEY ("document_id", "tenant_id") REFERENCES "import_documents"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "claim_documents" ADD CONSTRAINT "claim_documents_linked_by_id_fkey" FOREIGN KEY ("linked_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------------------------
-- List columns are never NULL (empty array instead).
-- ---------------------------------------------------------------------------------------------
ALTER TABLE "import_documents" ALTER COLUMN "review_reasons" SET DEFAULT '{}', ALTER COLUMN "review_reasons" SET NOT NULL;
ALTER TABLE "import_documents" ALTER COLUMN "warnings" SET DEFAULT '{}', ALTER COLUMN "warnings" SET NOT NULL;
ALTER TABLE "extracted_fields" ALTER COLUMN "review_reasons" SET DEFAULT '{}', ALTER COLUMN "review_reasons" SET NOT NULL;

-- ---------------------------------------------------------------------------------------------
-- CHECK constraints
-- ---------------------------------------------------------------------------------------------
ALTER TABLE "import_batches" ADD CONSTRAINT "import_batches_label_length"
  CHECK (label IS NULL OR char_length(label) BETWEEN 1 AND 120);

ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_display_name_length"
  CHECK (char_length(display_name) BETWEEN 1 AND 255);
-- 1 byte .. the production ceiling of IMPORT_MAX_FILE_BYTES (25 MiB).
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_size_range" CHECK (size_bytes BETWEEN 1 AND 26214400);
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_sha256_hex" CHECK (sha256 ~ '^[0-9a-f]{64}$');
-- Object keys always live under the row's own tenant prefix.
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_storage_key_tenant"
  CHECK (storage_key IS NULL OR storage_key LIKE 't/' || tenant_id::text || '/%');
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_text_key_tenant"
  CHECK (text_key IS NULL OR text_key LIKE 't/' || tenant_id::text || '/%');
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_stored_unless_rejected"
  CHECK (status IN ('REJECTED', 'FAILED') OR storage_key IS NOT NULL);
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_uploader_for_uploads"
  CHECK (source = 'EMAIL' OR uploaded_by_id IS NOT NULL);
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_source_ref_format"
  CHECK (source_ref IS NULL OR source_ref ~ '^[0-9a-f]{64}$');
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_reject_reason"
  CHECK (reject_reason IS NULL OR (status IN ('REJECTED', 'FAILED') AND reject_reason ~ '^[a-z_]{1,40}$'));
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_counts_nonneg"
  CHECK ((page_count IS NULL OR page_count >= 0) AND (char_count IS NULL OR char_count >= 0));
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_load_number_length"
  CHECK (load_number IS NULL OR char_length(load_number) BETWEEN 1 AND 100);
ALTER TABLE "import_documents" ADD CONSTRAINT "import_documents_provider_strings"
  CHECK (char_length(provider_name) BETWEEN 1 AND 40 AND char_length(provider_version) BETWEEN 1 AND 20 AND char_length(parser_version) BETWEEN 1 AND 20);

-- The N7 field-key allow-list: anything else never appears.
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_key_allowed" CHECK (key IN (
  'invoice.invoice_number', 'invoice.load_number', 'invoice.carrier', 'invoice.shipper', 'invoice.invoice_date',
  'invoice.total', 'invoice.charge.description', 'invoice.charge.amount',
  'rate_confirmation.load_number', 'rate_confirmation.carrier', 'rate_confirmation.linehaul_rate',
  'rate_confirmation.fuel_surcharge', 'rate_confirmation.detention_free_hours',
  'rate_confirmation.detention_rate_per_hour', 'rate_confirmation.detention_max_hours',
  'rate_confirmation.authorized_accessorials',
  'bol.load_number', 'bol.facility', 'bol.appointment_time', 'bol.arrival_time', 'bol.departure_time'));
-- Charge pairs (and only they) carry a group index.
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_group_index"
  CHECK ((key IN ('invoice.charge.description', 'invoice.charge.amount')) = (group_index IS NOT NULL) AND (group_index IS NULL OR group_index >= 0));
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_ordinal_nonneg" CHECK (ordinal >= 0);
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_lengths"
  CHECK (char_length(raw_value) <= 500 AND (value IS NULL OR char_length(value) <= 4000)
         AND (corrected_value IS NULL OR char_length(corrected_value) <= 4000)
         AND (excerpt IS NULL OR char_length(excerpt) <= 200));
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_confidence_range" CHECK (confidence BETWEEN 0 AND 1);
-- Provenance: pointer columns are all NULL iff the field was keyed in manually.
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_pointer_iff_extracted" CHECK (
  (origin = 'MANUAL' AND page IS NULL AND line IS NULL AND start_col IS NULL AND end_col IS NULL AND source_row IS NULL AND excerpt IS NULL)
  OR (origin = 'EXTRACTED' AND line IS NOT NULL AND start_col IS NOT NULL AND end_col IS NOT NULL AND excerpt IS NOT NULL));
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_pointer_ranges" CHECK (
  (page IS NULL OR page >= 1) AND (line IS NULL OR line >= 1) AND (source_row IS NULL OR source_row >= 1)
  AND (start_col IS NULL OR (start_col >= 0 AND end_col >= start_col)));
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_corrected_iff_status"
  CHECK ((status = 'CORRECTED') = (corrected_value IS NOT NULL));
ALTER TABLE "extracted_fields" ADD CONSTRAINT "extracted_fields_resolution_iff_status"
  CHECK ((status = 'PROPOSED') = (resolved_at IS NULL) AND (resolved_at IS NULL) = (resolved_by_id IS NULL));
-- At most one LIVE field per (document, key, group); a NULL group counts as group 0. Rejected fields
-- leave the index so a reviewer can key in a replacement (R47).
CREATE UNIQUE INDEX "extracted_fields_one_live_per_key" ON "extracted_fields"
  ("document_id", "key", (COALESCE("group_index", 0))) WHERE status <> 'REJECTED';

ALTER TABLE "import_review_decisions" ADD CONSTRAINT "import_review_decisions_reason_length"
  CHECK (char_length(reason) BETWEEN 10 AND 2000);
ALTER TABLE "import_review_decisions" ADD CONSTRAINT "import_review_decisions_hashes_hex"
  CHECK ((before_value_sha256 IS NULL OR before_value_sha256 ~ '^[0-9a-f]{64}$')
         AND (after_value_sha256 IS NULL OR after_value_sha256 ~ '^[0-9a-f]{64}$'));
ALTER TABLE "import_review_decisions" ADD CONSTRAINT "import_review_decisions_field_actions"
  CHECK ((action IN ('CONFIRM', 'CORRECT', 'REJECT', 'ADD')) = (field_id IS NOT NULL));

-- ---------------------------------------------------------------------------------------------
-- Row-level security (fail closed: without app.tenant_id nothing is visible or writable).
-- ---------------------------------------------------------------------------------------------
ALTER TABLE "import_batches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "import_batches" FORCE ROW LEVEL SECURITY;
CREATE POLICY "import_batches_tenant_isolation" ON "import_batches" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

ALTER TABLE "import_documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "import_documents" FORCE ROW LEVEL SECURITY;
CREATE POLICY "import_documents_tenant_isolation" ON "import_documents" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

ALTER TABLE "extracted_fields" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "extracted_fields" FORCE ROW LEVEL SECURITY;
CREATE POLICY "extracted_fields_tenant_isolation" ON "extracted_fields" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

ALTER TABLE "import_review_decisions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "import_review_decisions" FORCE ROW LEVEL SECURITY;
CREATE POLICY "import_review_decisions_tenant_isolation" ON "import_review_decisions" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

ALTER TABLE "claim_documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "claim_documents" FORCE ROW LEVEL SECURITY;
CREATE POLICY "claim_documents_tenant_isolation" ON "claim_documents" FOR ALL
  USING (tenant_id = fr_current_tenant()) WITH CHECK (tenant_id = fr_current_tenant());

-- ---------------------------------------------------------------------------------------------
-- Append-only and immutability triggers (fr_append_only comes from the init migration).
-- ---------------------------------------------------------------------------------------------
CREATE TRIGGER "import_batches_append_only" BEFORE UPDATE OR DELETE ON "import_batches" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "import_batches_no_truncate" BEFORE TRUNCATE ON "import_batches" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "import_review_decisions_append_only" BEFORE UPDATE OR DELETE ON "import_review_decisions" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "import_review_decisions_no_truncate" BEFORE TRUNCATE ON "import_review_decisions" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "claim_documents_append_only" BEFORE UPDATE OR DELETE ON "claim_documents" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "claim_documents_no_truncate" BEFORE TRUNCATE ON "claim_documents" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();

-- Import documents: identity/content columns never change; status moves only along the pipeline
-- (RECEIVED -> NEEDS_REVIEW|ACCEPTED|REJECTED|FAILED, NEEDS_REVIEW -> ACCEPTED|REJECTED); terminal rows
-- (ACCEPTED, REJECTED, FAILED) are frozen; object keys may only be cleared when the row is rejected or
-- failed (object deleted), and the derived-text key may only be set once while the row is being parsed.
CREATE FUNCTION fr_import_document_update_guard() RETURNS trigger
  LANGUAGE plpgsql
  AS $$
BEGIN
  IF NEW.id IS DISTINCT FROM OLD.id OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
     OR NEW.batch_id IS DISTINCT FROM OLD.batch_id OR NEW.uploaded_by_id IS DISTINCT FROM OLD.uploaded_by_id
     OR NEW.source IS DISTINCT FROM OLD.source OR NEW.source_ref IS DISTINCT FROM OLD.source_ref
     OR NEW.display_name IS DISTINCT FROM OLD.display_name OR NEW.detected_type IS DISTINCT FROM OLD.detected_type
     OR NEW.size_bytes IS DISTINCT FROM OLD.size_bytes OR NEW.sha256 IS DISTINCT FROM OLD.sha256
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'import_document_immutable' USING ERRCODE = 'P0001';
  END IF;
  IF OLD.status IN ('ACCEPTED', 'REJECTED', 'FAILED') THEN
    RAISE EXCEPTION 'import_document_terminal' USING ERRCODE = 'P0001';
  END IF;
  IF NEW.status IS DISTINCT FROM OLD.status
     AND NOT ((OLD.status = 'RECEIVED' AND NEW.status IN ('NEEDS_REVIEW', 'ACCEPTED', 'REJECTED', 'FAILED'))
              OR (OLD.status = 'NEEDS_REVIEW' AND NEW.status IN ('ACCEPTED', 'REJECTED'))) THEN
    RAISE EXCEPTION 'invalid_import_document_transition' USING ERRCODE = 'P0001';
  END IF;
  IF NEW.storage_key IS DISTINCT FROM OLD.storage_key
     AND NOT (OLD.storage_key IS NOT NULL AND NEW.storage_key IS NULL AND NEW.status IN ('REJECTED', 'FAILED')) THEN
    RAISE EXCEPTION 'import_document_storage_key' USING ERRCODE = 'P0001';
  END IF;
  IF NEW.text_key IS DISTINCT FROM OLD.text_key
     AND NOT (OLD.text_key IS NULL AND NEW.text_key IS NOT NULL AND OLD.status = 'RECEIVED')
     AND NOT (OLD.text_key IS NOT NULL AND NEW.text_key IS NULL AND NEW.status IN ('REJECTED', 'FAILED')) THEN
    RAISE EXCEPTION 'import_document_text_key' USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER "import_documents_update_guard" BEFORE UPDATE ON "import_documents" FOR EACH ROW EXECUTE FUNCTION fr_import_document_update_guard();
CREATE TRIGGER "import_documents_no_delete" BEFORE DELETE ON "import_documents" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "import_documents_no_truncate" BEFORE TRUNCATE ON "import_documents" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();

-- Extracted fields: only the resolution columns may change, exactly once (PROPOSED -> resolved).
CREATE FUNCTION fr_extracted_field_update_guard() RETURNS trigger
  LANGUAGE plpgsql
  AS $$
BEGIN
  IF (to_jsonb(NEW) - 'status' - 'corrected_value' - 'resolved_by_id' - 'resolved_at')
     IS DISTINCT FROM (to_jsonb(OLD) - 'status' - 'corrected_value' - 'resolved_by_id' - 'resolved_at') THEN
    RAISE EXCEPTION 'extracted_field_immutable' USING ERRCODE = 'P0001';
  END IF;
  IF NOT (OLD.status = 'PROPOSED' AND NEW.status IN ('CONFIRMED', 'CORRECTED', 'REJECTED')) THEN
    RAISE EXCEPTION 'invalid_extracted_field_transition' USING ERRCODE = 'P0001';
  END IF;
  RETURN NEW;
END
$$;

CREATE TRIGGER "extracted_fields_update_guard" BEFORE UPDATE ON "extracted_fields" FOR EACH ROW EXECUTE FUNCTION fr_extracted_field_update_guard();
CREATE TRIGGER "extracted_fields_no_delete" BEFORE DELETE ON "extracted_fields" FOR EACH ROW EXECUTE FUNCTION fr_append_only();
CREATE TRIGGER "extracted_fields_no_truncate" BEFORE TRUNCATE ON "extracted_fields" FOR EACH STATEMENT EXECUTE FUNCTION fr_append_only();

-- ---------------------------------------------------------------------------------------------
-- Least-privilege grants for the runtime role (no TRUNCATE, no DELETE, no DDL). Enum types keep the
-- PostgreSQL default USAGE for PUBLIC (as in the init migration).
-- ---------------------------------------------------------------------------------------------
REVOKE ALL ON "import_batches", "import_documents", "extracted_fields", "import_review_decisions", "claim_documents" FROM PUBLIC;
REVOKE ALL ON FUNCTION fr_import_document_update_guard() FROM PUBLIC;
REVOKE ALL ON FUNCTION fr_extracted_field_update_guard() FROM PUBLIC;
GRANT SELECT, INSERT ON "import_batches", "import_review_decisions", "claim_documents" TO freight_app;
GRANT SELECT, INSERT ON "import_documents" TO freight_app;
GRANT UPDATE ("status", "reject_reason", "review_reasons", "warnings", "doc_type", "doc_type_basis", "page_count",
              "char_count", "load_number", "text_key", "provider_name", "provider_version", "parser_version",
              "storage_key", "parsed_at", "updated_at") ON "import_documents" TO freight_app;
GRANT SELECT, INSERT ON "extracted_fields" TO freight_app;
GRANT UPDATE ("status", "corrected_value", "resolved_by_id", "resolved_at") ON "extracted_fields" TO freight_app;
